# Site settings
title: PyDataFest Amsterdam
description:
  PyData Amsterdam will not be held in-person this year <br>
  In its stead, we are glad to annouce *PyDataFest Amsterdam 2020*! <br>
  <br>
  A week-long digital event from June 15th till June 20th <br>
  with a mix of talks, interviews, workshops, discussions <br>
  and open-source sprints. <br>
  <br>
  All proceeds of the conference go to [NumFocus](https://numfocus.org/), <br>
  a non-profit that helps sustain Python's scientific computing ecosystem
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://amsterdam.pydata.org" # the base hostname & protocol for your site


future: true

tickets_url:
cfp_url: pages/cfp

dates:
location:

greeting:
  title: About PyData
  text:
    PyData is an educational program of NumFOCUS, a 501(c)3 non-profit organization in the United States.
    PyData provides a forum for the international community of users and developers of data analysis tools to
    share ideas and learn from each other.<br /><br />

    The global PyData network promotes discussion of best practices, new approaches,
    and emerging technologies for data management, processing, analytics, and visualization.
    PyData communities approach data science using many languages, including (but not limited to) Python, Julia, and R.<br /><br />

    The PyData Code of Conduct governs this conference. To discuss any issues or concerns relating to the code of
    conduct or the behavior of anyone at a PyData conference (or meetup), please contact NumFOCUS Executive Director 
    Leah Silen (+1 512-222-5449; leah@numfocus.org ) or the local organisers at amsterdam@pydata.org.

social:
  twitter: https://twitter.com/PyDataAmsterdam
  github: https://github.com/PyDataAmsterdam

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

include: ['_pages']

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/PyDataAmsterdam
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/pydataamsterdam

# Build settings
markdown: kramdown

destination: ./build
